logins/urls.py
app_name = 'login'
urlpatterns = [
    url('^$', views.home, name='home'),
    url('^do_login/$', views.do_login, name='do_login')
]

@login_required(login_url='/login/do_login')
def home(request):
    return render(request,
                  'home.html',
                  {'username': request.user.username})

mysite_login/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),

]

logins/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
'''
import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone


@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


    def __str__(self):
        return self.question_text




@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
'''

from django.db import models

class User(models.Model):
    username = models.CharField()
    headImg = models.

logins/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

logins/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>主页</title>
<body>
    欢迎，{{ username }}
</body>

</html>

logins/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <form action="{% url 'login:do_login' %}" method="post">
        {% csrf_token %}
        <label for="username">用户名：</label>
        <input id="username" type="text" name="username" value="{{ username }}"><br/>
        <label for="password">密码：</label>
        <input id="password" type="password" name="password" value="{{ password }}"><br/>
        <input type="submit" value="登录">
    </form>
</body>

</html>

logins/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>zhuce</title>
</head>
<body>
<form action="{% url 'register' %}" method="post" accept-charset="utf-8"enctype="multipart/form-data" >
   {% csrf_token %}
   <input type="text" name="username"id="username" placeholder="请输入手机号" >
   <input type="password"  name="password" id="password" placeholder="请输入6-12位密码" >
   <input type="submit" class="submit" value="立即注册">
 </form>
</body>
</html>